name: Hugo Build and Deploy

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install Hugo
        run: |
          wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.60.0/hugo_extended_0.60.0_Linux-64bit.deb
          sudo dpkg -i /tmp/hugo.deb
      
      - name: Build Site with Hugo
        run: hugo
      
      - name: Make deploy.sh Executable
        run: chmod +x ./deploy.sh

      - name: Deploy
        run: ./deploy.sh
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}